site_name: My Profile
site_url: https://sitename.example
theme:
   name: material
   font:
    text: Merriweather Sans
    code: Red Hat Mono
   icon:
    logo: fontawesome/solid/r
   favicon: assets/favicon.ico
   features:
    - navigation.footer
    - navigation.tabs
   palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: indigo

    # Light Mode
    - scheme: teal
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: indigo
plugins:
  - search:
  - blog:
      blog_dir: .

markdown_extensions:
  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

